### ISSUE TITLE
Push pudates to v1.x branch after releases.

### ISSUE THREAD

**Issue by gr2m** [cycjimmy/semantic-release-action#1]
Hey Geoffrey, this is a great action, thanks for sharing!

I would recommend to push to a `v1.x` branch after a successful release, so you don't have to define a specific tag name when you setup the action, but can do `@v1.x`. Here is an example setup I that use for my actions: https://github.com/gr2m/create-or-update-pull-request-action/blob/ba2dce338c7d56fbfb7c4e1e878b9d29ce20e8ae/.github/workflows/release.yml

I had to use `GR2M_PAT_FOR_SEMANTIC_RELEASE` because I use the `git` plugin and have branch protection enabled, and the `GITHUB_TOKEN` cannot push to master because of that.

**Comment by cycjimmy** [comment]
This is really a very good idea and exactly what I want. 
I have pushed updates to v1 branch for [recommended version by GitHub](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations). 

Thank you for your suggestion.

**Comment by gr2m** [comment]
Awsome, glad it was helpful :)

**Comment by felipecassiors** [comment]
This does the same in a more elegant way (using major git tags) https://github.com/marketplace/actions/actions-tagger
