### ISSUE TITLE
Worth mentioning that for extra_plugins to work, one must define them in the release config

### ISSUE THREAD

**Issue by sudkumar** [cycjimmy/semantic-release-action#10]
**Is your feature request related to a problem? Please describe.**
I was using this action and saw the `extra_plugins` configuration option. I was using a release config but I removed it (less configuration on local =D) and added the extra plugins (`git` and `changelog`) to the actions only.

```bash
rm release.config.js
```

```diff
+       extra_plugins: |
+          @semantic-release/git
+          @semantic-release/changelog@3.0.0
```

Releases were working (github and all other default plugins) but `git` and `changelog` plugins were not loaded by the semantic-release. After testing for 3-4 times, when it was not working, I reverted back to using `release.config.js` and stuff started working.

**Describe the solution you'd like**
I think it is worth mentioning in the docs that if we pass the `extra_plugins` configuration, these plugins must also be defined in the release configuration else these plugins will not be used by the `semantic-release`. Adding `extra_plugins` only installs the plugins (so we don't have to) and does not update the release plugins configuration.

**Comment by sudkumar** [comment]
@cycjimmy  I am happy to create a PR if you think other people may benefit from it or have encountered it.

**Comment by cycjimmy** [comment]
The configuration file is necessary that can configure more complicated configuration items. The original purpose of extra_plugins is only to install additional plugins other than the built-in plugins in semantic-release. If it will cause misunderstanding, it needs to be clearer in the documentation. And your contribution to semantic-release-action is more than welcome!

**Comment by sudkumar** [comment]
@cycjimmy :) PR on the way.
