### ISSUE TITLE
Allow main as default branch

### ISSUE THREAD

**Issue by nickmccurdy** [cycjimmy/semantic-release-action#125]
**Describe the bug**
See https://github.com/semantic-release/semantic-release/issues/1581

**Workflow**
N/A

**Expected behavior**
Repository with `main` branch is released automatically.

**Additional context**
Repository with `main` branch is not released automatically.

**Comment by cycjimmy** [comment]
I still think it should stay the same as the semantic-release configuration for now.
And we can manually add the `main` branch to the workflow file to meet our needs.
For example: 
```yaml
steps:
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    with:
      branches: |    
        [
          '+([0-9])?(.{+([0-9]),x}).x',
          'master', 
          'main', 
          'next', 
          'next-major', 
          {
            name: 'beta', 
            prerelease: true
          }, 
          {
            name: 'alpha', 
            prerelease: true
          }
        ]
...
```

**Comment by kddsultan** [comment]
@cycjimmy, 

Does the above config release `prerelease` for `main`?

**Comment by adrianschmidt** [comment]
> Does the above config release prerelease for main?

No, that config would create a regular release on either `main` or `master`. But if you have both a `main` and a `master` branch, semantic-release should detect that there are two existing branches on which the same release could potentially be created, and refuse to create a release.
