### ISSUE TITLE
Warning in workflow about set-output

### ISSUE THREAD

**Issue by ianong-rsi** [cycjimmy/semantic-release-action#127]
**Describe the bug**
Warning when running the semantic-release-action workflow.
![image](https://user-images.githubusercontent.com/107639194/195703182-728e8034-b302-4515-9db9-5fc20e0144d1.png)

**Comment by OlivierCuyp** [comment]
I guess the only thing to fix this, is too upgrade the `@actions/core` version to the version [1.10.0](https://www.npmjs.com/package/@actions/core).
For now it is still on the version [1.6.0](https://github.com/cycjimmy/semantic-release-action/blob/main/package.json#L24)
