### ISSUE TITLE
Allow tag format parameter

### ISSUE THREAD

**Issue by dezkareid** [cycjimmy/semantic-release-action#152]
**Is your feature request related to a problem? Please describe.**
I'm working on a monorepo architecture with multiple projects and I need set different tags for every package

**Describe the solution you'd like**
I like to add tag_format input to customize it,  I've made a [PR](https://github.com/dezkareid/semantic-release-action/pull/1) but on my forked version

**Describe alternatives you've considered**

**Additional context**

**Comment by cycjimmy** [comment]
That‘s ok. Can you submit a PR directly to this repository?
