### ISSUE TITLE
Get version from dry-run mode.

### ISSUE THREAD

**Issue by VisualBean** [cycjimmy/semantic-release-action#166]
When running with `dry_run: true`, `new_release_version` is not set.
It would be quite nice to be able to get the new version number output, from dryruns

**Comment by VisualBean** [comment]
It was me all along.

**Comment by scott-hannan** [comment]
Hey @VisualBean, I am facing a similar problem. Trying to run this on a pull request to preview a release version. What did you end up doing to get the new version from a dry run? Any help appreciated, thanks!

**Comment by VisualBean** [comment]
> Hey @VisualBean, I am facing a similar problem. Trying to run this on a pull request to preview a release version. What did you end up doing to get the new version from a dry run? Any help appreciated, thanks! 

I think I just ended up using the 'new_release_published' and not looking at the'future' version so to speak.
