### ISSUE TITLE
Protected branch update failed for refs/heads/master

### ISSUE THREAD

**Issue by bennypowers** [cycjimmy/semantic-release-action#18]
**Describe the bug**
```
[12:44:09 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://x-access-token:[secure]@github.com/bennypowers/stripe-elements.git HEAD:master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 2 of 2 required status checks are expected.        
To https://github.com/bennypowers/stripe-elements.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://x-access-token:[secure]@github.com/bennypowers/stripe-elements.git'
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async push (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://x-access-token:[secure]@github.com/bennypowers/stripe-elements.git HEAD:master',
  command: 'git push --tags https://x-access-token:[secure]@github.com/bennypowers/stripe-elements.git HEAD:master',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \n' +
    'remote: error: 2 of 2 required status checks are expected.        \n' +
    'To https://github.com/bennypowers/stripe-elements.git\n' +
    ' ! [remote rejected] HEAD -> master (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://x-access-token:[secure]@github.com/bennypowers/stripe-elements.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
##[error]Error: Command failed with exit code 1: git push --tags ***github.com/bennypowers/stripe-elements.git HEAD:master
```

**Workflow**
https://github.com/bennypowers/stripe-elements/blob/e347aaa183cef7604f00e192dd3a9da05e41f272/.github/workflows/release.yml#L44-L63

**Comment by bennypowers** [comment]
I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.

**Comment by ferserrano-contino** [comment]
> I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.

Hi @bennypowers I'm having the exact same issue. Could you please share how exactly you fixed it when saying you passed a write-enabled github PAT?

Thanks!

**Comment by bennypowers** [comment]
> > I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.
> 
> Hi @bennypowers I'm having the exact same issue. Could you please share how exactly you fixed it when saying you passed a write-enabled github PAT?
> 
> Thanks!

create a classic github personal access token with write permissions to your repo, then pass that to the action at `GITHUB_TOKEN`, per the readme.

**Comment by ferserrano-contino** [comment]
> > > I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.
> > 
> > 
> > Hi @bennypowers I'm having the exact same issue. Could you please share how exactly you fixed it when saying you passed a write-enabled github PAT?
> > Thanks!
> 
> create a classic github personal access token with write permissions to your repo, then pass that to the action at `GITHUB_TOKEN`, per the readme.

Thanks for getting back to me. I was hoping it would be something else as I have already tried exactly what you said, but yet no luck.

**Comment by mauricio-liatrio** [comment]
> > > > I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.
> > > 
> > > 
> > > Hi @bennypowers I'm having the exact same issue. Could you please share how exactly you fixed it when saying you passed a write-enabled github PAT?
> > > Thanks!
> > 
> > 
> > create a classic github personal access token with write permissions to your repo, then pass that to the action at `GITHUB_TOKEN`, per the readme.
> 
> Thanks for getting back to me. I was hoping it would be something else as I have already tried exactly what you said, but yet no luck.

@ferserrano-contino were you able to resolve the problem. I have the exact same issue.

**Comment by ferserrano-contino** [comment]
> > > > > I solved this issue by passing a write-enabled github PAT as GITHUB_TOKEN. the token supplied by the actions env is insufficient.
> > > > 
> > > > 
> > > > Hi @bennypowers I'm having the exact same issue. Could you please share how exactly you fixed it when saying you passed a write-enabled github PAT?
> > > > Thanks!
> > > 
> > > 
> > > create a classic github personal access token with write permissions to your repo, then pass that to the action at `GITHUB_TOKEN`, per the readme.
> > 
> > 
> > Thanks for getting back to me. I was hoping it would be something else as I have already tried exactly what you said, but yet no luck.
> 
> @ferserrano-contino were you able to resolve the problem. I have the exact same issue.

Yes, I was. Solved that issue by passing the PAT token at the checkout step. After that, it picks it up with the correct permissions.
steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_TOKEN }}
