### ISSUE TITLE
action should fail if initial npm install fails

### ISSUE THREAD

**Issue by soojeen-park-mark43** [cycjimmy/semantic-release-action#224]
**Describe the bug**
If you encounter an error during the initial npm install https://github.com/cycjimmy/semantic-release-action/blob/b2ec2708bf20a96621f9926d1e4c73c7b57a89f9/index.js#L7

it does not fail the overall action.

the code ends up catching and swallowing any errors here and the action is marked as success.
https://github.com/cycjimmy/semantic-release-action/blob/b2ec2708bf20a96621f9926d1e4c73c7b57a89f9/index.js#L19

**Workflow**
If applicable, provide a workflow file to help explain your problem.

**Expected behavior**
I would expect any error in the initial setup to fail the action.

**Additional context**
see here for how other errors are caught and sent to `core.setFailed`.
https://github.com/cycjimmy/semantic-release-action/blob/b2ec2708bf20a96621f9926d1e4c73c7b57a89f9/src/index.js#L46

**Comment by cycjimmy** [comment]
You are correct; I will make adjustments to this later.

**Comment by cycjimmy** [comment]
I reverted this fix because when npm modules were not installed, it could not find the '@actions/core' module and could not call the `core.setFailed`.
