### ISSUE TITLE
Ability to split steps for baking version

### ISSUE THREAD

**Issue by Renari** [cycjimmy/semantic-release-action#32]
**Is your feature request related to a problem? Please describe.**
When generating a build I'd like to bake the version into the application so that I can check which version is being run. e.g. `myprogram --version` -> `1.0.3`. The problem is semantic-release-action generates the version and releases in the same setp.

**Describe the solution you'd like**
I'd like to be able to generate the version before doing release so that `new_release_version` will be populated but a release will not be made. Then I could build a release in this order:

- get version number
- bake version number into application
- build 
- publish release

currently it works like this:

- build
- get version number and publish release

**Comment by cycjimmy** [comment]
I think you can use the @semantic-release/exec plugin to achieve your purpose. Just execute your build command before publishing a release. Please see [@semantic-release/exec](https://github.com/semantic-release/exec) for details.

**Comment by Renari** [comment]
I don't think this is actually the case:
https://github.com/semantic-release/exec/issues/107

**Comment by cycjimmy** [comment]
> I don't think this is actually the case:
> [semantic-release/exec#107](https://github.com/semantic-release/exec/issues/107)

Is there anything problem with that issue?

**Comment by Renari** [comment]
I ended up getting it working:
```
      [
        "@semantic-release/exec",
        {
          "prepareCmd": "sed -i 's/<version>/${nextRelease.version}/' src/index.ts"
        }
      ]
```
