### ISSUE TITLE
Expose pre-release version and beta/alpha branch

### ISSUE THREAD

**Issue by techninja** [cycjimmy/semantic-release-action#35]
**Is your feature request related to a problem? Please describe.**
I need to use the release trigger in Github Actions manage a mirror repo on release and need to automate what happens on specific version for pre-release. Looks like the branch name (EG `alpha`/`beta`) and the specific pre-release version(single digit that follows) aren't exposed to the `steps.semantic.outputs`.

**Describe the solution you'd like**
I'd love to at least three variables exposed on release for prereleases:

- `new_prerelease_published`: Would only `true` if time `new_release_published` is, _**and**_ the release branch is configured as `"prerelease": true`
- `new_prerelease_branch`: As per the default in semantic release, would be the name of the branch, likely `alpha` or `beta`
- `new_prerelease_version`: Whatever the number added after the branch name is, basically a fourth pre-release specific version number.

**Describe alternatives you've considered**
This information simply isn't available directly for CI steps without doing CI level string ops.

**Comment by cycjimmy** [comment]
I cannot find whether it is prerelease in semantic-release javascript API, so I add the output of `new_release_channel`. You can use it to judge by yourself.

For example, if new_release_channel is alpha and the `alpha` branch in your branches configuration is `prerelease`, you can determine the release is prerelease.
