### ISSUE TITLE
Avoid adding custom plugins in package.json

### ISSUE THREAD

**Issue by frederikhors** [cycjimmy/semantic-release-action#39]
Why if I want to use other plugins (such as `@semantic-release/changelog` and `@semantic-release/git`) do I have to add them to `package.json`?

Is there any way to avoid?

It would be very convenient especially in projects where it is not possible to touch the `package.json`.

Can you detect them and `npm install ...` automagically in a "before step"?

Thank you for your amazing work.

**Comment by cycjimmy** [comment]
No need to put `@semantic-release/changelog`  to `package.json`, and just write it to the `extra_plugins` list. 

See [extra_plugins](https://github.com/cycjimmy/semantic-release-action#extra_plugins).
