### ISSUE TITLE
How would you deal with transpiled files?

### ISSUE THREAD

**Issue by bahmutov** [cycjimmy/semantic-release-action#4]
I am using your action (thank you for making it) to automate releasing https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml

Before publishing I would like to transpile code into `dist` folder, which is normally Git-ignored

```json
{
  "scripts": {
    "prepublishOnly": "ncc build -o dist index.js && git add -f dist"
  }
}
```

NPM includes `dist` folder just fine
```
195kB  dist/index.js
196kB  [1308ms] - ncc 0.20.5
npm notice 
npm notice 📦  @cypress/github-action@1.2.1
npm notice === Tarball Contents === 
npm notice 200.1kB dist/index.js 
npm notice 1.5kB   dist/thread.js
npm notice 1.1kB   package.json  
npm notice 1.1kB   LICENSE.md    
npm notice 989B    README.md     
npm notice 437B    action.yml    
npm notice === Tarball Details === 
npm notice name:          @cypress/github-action                  
npm notice version:       1.2.1                                   
npm notice package size:  50.4 kB                                 
npm notice unpacked size: 205.1 kB                                
npm notice shasum:        ba48dce87ce6b1be22d368eeb830b15153e3a57a
npm notice integrity:     sha512-EfLyrw6vk3qj6[...]ch4R10tXxL8sw==
npm notice total files:   6                                       
npm notice 
+ @cypress/github-action@1.2.1
```

But GitHub does not include `dist` folder - because we only included the `dist` folder locally. Is there a way to "amend" the commit and push the full tar to GitHub to include transpiled artifacts?

**Comment by bahmutov** [comment]
Note: for now I have started committing `dist` folder, but would love not to do it

**Comment by cblanc** [comment]
Have you tried adding a `- run: npm run build` step before the semantic release action?

**Comment by cblanc** [comment]
Have you tried adding a - run: npm run build step before the semantic release action?

**Comment by cycjimmy** [comment]
Add the `files` attribute to package.json
```js
{
  ...,
  "files": [
     "/dist"
  ],
  ...
}
```

**Comment by bahmutov** [comment]
Thank you @cycjimmy - I am looking at https://github.com/semantic-release/git - since it can modify the assets included with the release on GitHub (including `dist` in the published NPM package is easy and working). I will close this issue after trying it out later in the week

**Comment by cycjimmy** [comment]
The issue is inactive for a long time. I will close it.
