### ISSUE TITLE
How to change root directory 

### ISSUE THREAD

**Issue by kdichev** [cycjimmy/semantic-release-action#50]
We are using workspaces and our to be deployed package is in packages/the-package. How do I tell the gh action to switch to the root repo of the package rather than doing it from root of the whole monorepo?

**Comment by cycjimmy** [comment]
It seems that this is not in the scope of this action. It is recommended to publish each package independently.

Besides, you can try setting`pkgRoot` property of `@semantic-release/npm` plugin in your semantic release configuration.

```js
module.exports = {
  ...	
  "plugins": [
    ...
    ["@semantic-release/npm", {
      "pkgRoot": "your-package-dist"
    }]
    ...	
  ]
}
```

See [@semantic-release/npm options](https://github.com/semantic-release/npm#options) for more details.

**Comment by svrooij** [comment]
@cycjimmy I have this library where the package (and all related files I want to release) are in a subfolder `/generator/sonos-docs` under the [repo](https://github.com/svrooij/sonos-api-docs). Would it be possible to support something like the [working-directory](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun) that you can use with the regular run command.

I've now fixed it with this https://github.com/svrooij/sonos-api-docs/blob/212f71c195a4881ecb73e1f435f8203358d5a479/.github/workflows/generator.yml#L53-L59 but that means I can no longer use the outputs of your action.

Use-cases for not using the root directory:

- The package and package.json are not in the root folder
- Multiple packages in a mono-repository
