### ISSUE TITLE
Create release on workflow which is triggered by a pull request

### ISSUE THREAD

**Issue by lodeli-lulu** [cycjimmy/semantic-release-action#54]
Hello,

I want to create a pre-release, if a pull request was opened. In my workflow, I noticted a message from release action which is saying: This run was triggered by a pull request and therefore a new version won't be published. 

Is there a way to create a pre-release on pull requests?

Best wishes

**Comment by adamdehaven** [comment]
@cycjimmy is there a way to do this? I'd like to perform a dry-run on a PR branch so that I can output what the new published version _would be_ if the PR were to be merged.
