### ISSUE TITLE
Is it possible to use this action to get the latest release version?

### ISSUE THREAD

**Issue by yrshaikh** [cycjimmy/semantic-release-action#56]
**Is your feature request related to a problem? Please describe.**
I do already see when running in dry mode, the action already knows about the current version
`[7:53:22 AM] [semantic-release] › ℹ  Found git tag v1.2.4 associated with version 1.2.4 on branch master`

Is there a way to read it, as output or something?

**Comment by trimble** [comment]
Is the output "new_release_version" (https://github.com/cycjimmy/semantic-release-action#outputs) what you're looking for?
