### ISSUE TITLE
Cannot execute multiple times in same job

### ISSUE THREAD

**Issue by McManning** [cycjimmy/semantic-release-action#57]
**Describe the bug**

Hi all - I have an action that runs semantic-release-action in two steps, first one does a dry run to grab release version information needed for my build steps and the second performs the actual release once all the build steps have completed. 

The first run happens as expected, but the second will never execute. This is all that I get as an output:

```
Run cycjimmy/semantic-release-action@v2
  with:
  env:
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
    GITHUB_TOKEN: ***
added 323 packages in 10.813s

npm WARN prepare removing existing node_modules/ before installation
```

**Workflow**

This is the workflow for the project I'm testing with that fails to perform any action at the "Publish to GitHub" step - https://github.com/McManning/tmp-release-ci/blob/master/.github/workflows/publish.yml#L34-L38

**Expected behavior**

Deploys release to Github on the second run

**Comment by McManning** [comment]
I tested this with a workflow that runs semantic-release-action twice (dry run first) and got the same error.

Workflow file here: https://github.com/McManning/tmp-release-ci/actions/runs/729625406/workflow

**Comment by denouche** [comment]
Hello,
Same thing for me here.
I want to run a dry-run step before my build, build my artifact, and then execute the release without the dry-run option. The second release step does not work.
I guess the warning `npm WARN prepare removing existing node_modules/ before installation` displayed the second time make the process stopping here: https://github.com/cycjimmy/semantic-release-action/blob/master/index.js#L11
