### ISSUE TITLE
AgregateError: HttpError: You have exceeded a secondary rate limit.

### ISSUE THREAD

**Issue by trombini77** [cycjimmy/semantic-release-action#86]
**Describe the bug**
It is not common, but in the last 12 months I guess this is the second time that I got the following error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13336060/144640730-a96c014c-5508-4447-b6df-7c74acdcfc14.png)

**Workflow**
the steps running it in the job are:
```
  release:
    name: CI Release
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          branches: |
            [
              'master',
              {
                name: 'staging',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
I expected not have this kind of error and it works fine.

**Additional context**

**Comment by iamludal** [comment]
This issue is not related to this action, but with the GitHub API.

**Comment by TMInnovations** [comment]
Here's one possible workaround + fix in process: https://github.com/semantic-release/github/pull/487#issuecomment-1486298997
